version: '3'
services:
  elasticsearch:
    image: bitnami/elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=elastic
    ports:
      - "9200:9200"
    networks:
      - elk

  kibana:
    image: bitnami/kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=elastic
    ports:
      - "5601:5601"
    networks:
      - elk

networks:
  elk:
    driver: bridge